language: php
php:
  - 5.3
  - 5.4
before_script:
  - mysql -e 'create database buckutt_test;'
  - mysql -u root buckutt_test < dev_structure.sql
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - cd tests/
  - mkdir logs
  - chmod 777 logs
  - cp config.inc.dist.php config.inc.php
script: ./phpunit --coverage-text .

